# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-14 12:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('stregsystem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stregsystem.Member', null=True)),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stregsystem.Room')),
                ('sale_id_tmp', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='sale',
            name='sale_list',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='stregsystem.SaleList', null=True),
            preserve_default=False,
        ),
    ]
