# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-14 13:04
from __future__ import unicode_literals

from django.db import migrations, models

def extract_sale_list(apps, schema_editor):
    Sale = apps.get_model("stregsystem", "Sale")
    SaleList = apps.get_model("stregsystem", "SaleList")
    Member = apps.get_model("stregsystem", "Member")

    for sale in Sale.objects.all():
        print(sale.id)
        try:
            myMember = sale.member
        except Member.DoesNotExist:
            print("REMOVED")
            continue

        newlist = SaleList(
            member = myMember,
            room = sale.room,
            timestamp = sale.timestamp
        )
        newlist.save()
        newlist.sale_set.add(sale)

class Migration(migrations.Migration):

    dependencies = [
        ('stregsystem', '0002_auto_20170314_1253'),
    ]

    operations = [
        migrations.RunSQL("DELETE FROM stregsystem_sale WHERE member_id = 0"),
        migrations.RunSQL("INSERT INTO stregsystem_salelist(timestamp, member_id, room_id, sale_id_tmp) SELECT timestamp, member_id, room_id, id FROM stregsystem_sale;"),
        # migrations.RunSQL("REPLACE INTO stregsystem_sale( id, timestamp, price, member_id, product_id, room_id, sale_list_id) SELECT s.id, s.timestamp, s.price, s.member_id, s.product_id, s.room_id, l.id FROM stregsystem_sale AS s JOIN stregsystem_salelist AS l ON s.id = l.sale_id_tmp;"), Works in sqlite, slow in mysql
        migrations.RunSQL("UPDATE stregsystem_sale JOIN stregsystem_salelist as l ON stregsystem_sale.id = l.sale_id_tmp SET sale_list_id=l.id;"),
    ]
