# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-15 09:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stregsystem', '0003_auto_20170314_1304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='member',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='room',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='timestamp',
        ),
        migrations.AlterField(
            model_name='sale',
            name='sale_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stregsystem.SaleList'),
        ),
        migrations.RemoveField(
            model_name='salelist',
            name='sale_id_tmp',
        ),
    ]
